[package]
name = "solar-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
rayon = "1.8.1"
anyhow ="1.0.80"
candle-core = "0.3.3"
